'use client';

import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAdminApi } from '@/lib/admin-api';
import { ROLES, type Role } from '@/types';
import { validate, type UserFormValues } from './UserFormModal';

const empty: UserFormValues = {
  email: '',
  name: '',
  role: 'learner',
  department: '',
  isActive: true,
};

export function CreateUserForm({ open, onClose }: { open: boolean; onClose: () => void }) {
  const api = useAdminApi();
  const queryClient = useQueryClient();

  const [values, setValues] = useState<UserFormValues>(empty);
  const [sendWelcomeEmail, setSendWelcomeEmail] = useState(true);
  const [errors, setErrors] = useState<Partial<Record<keyof UserFormValues, string>>>({});

  const create = useMutation({
    mutationFn: () =>
      api.createUser({
        email: values.email.trim(),
        name: values.name.trim(),
        role: values.role,
        department: values.department || undefined,
        sendWelcomeEmail,
      }),
    onSuccess: (user) => {
      queryClient.invalidateQueries({ queryKey: ['admin', 'users'] });
      // The temporary password is shown once and never stored client-side.
      toast.success(`Created ${user.email}`, {
        description: user.temporaryPassword
          ? `Temporary password: ${user.temporaryPassword}`
          : undefined,
        duration: 15000,
      });
      setValues(empty);
      onClose();
    },
    onError: (err: Error) => toast.error('Could not create user', { description: err.message }),
  });

  const set = <K extends keyof UserFormValues>(key: K, value: UserFormValues[K]) =>
    setValues((v) => ({ ...v, [key]: value }));

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const found = validate(values);
    setErrors(found);
    if (Object.keys(found).length === 0) create.mutate();
  };

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Create new user</DialogTitle>
          <DialogDescription>
            A temporary password is generated by the server and shown once.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={submit} className="space-y-4" noValidate>
          <div className="space-y-2">
            <Label htmlFor="new-email">Email</Label>
            <Input
              id="new-email"
              type="email"
              value={values.email}
              onChange={(e) => set('email', e.target.value)}
            />
            {errors.email && (
              <p role="alert" className="text-sm text-destructive">
                {errors.email}
              </p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="new-name">Name</Label>
            <Input id="new-name" value={values.name} onChange={(e) => set('name', e.target.value)} />
            {errors.name && (
              <p role="alert" className="text-sm text-destructive">
                {errors.name}
              </p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="new-role">Role</Label>
            <select
              id="new-role"
              value={values.role}
              onChange={(e) => set('role', e.target.value as Role)}
              className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            >
              {ROLES.map((r) => (
                <option key={r} value={r}>
                  {r[0].toUpperCase() + r.slice(1)}
                </option>
              ))}
            </select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="new-department">Department (optional)</Label>
            <Input
              id="new-department"
              value={values.department}
              onChange={(e) => set('department', e.target.value)}
            />
          </div>

          <div className="flex items-center gap-2">
            <Checkbox
              id="welcome"
              checked={sendWelcomeEmail}
              onCheckedChange={(checked) => setSendWelcomeEmail(checked === true)}
            />
            <Label htmlFor="welcome" className="font-normal">
              Send welcome email
            </Label>
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose} disabled={create.isPending}>
              Cancel
            </Button>
            <Button type="submit" disabled={create.isPending}>
              {create.isPending ? 'Creating…' : 'Create User'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
